### ISSUE TITLE
VectrasVM unable to open

### ISSUE THREAD

**Issue by CreaGab** [epicstudios856/Vectras-VM-Android#38]
Hi developer,

I currently have an issue opening the app on Android 14 (S24 Ultra).

It shows "command failed with exit code 1"
What can be done to not get this error?

Thanks in advance!
![Screenshot_20240413_194946_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/88980315/12c37d97-10b6-456e-a642-a821ab862fde)

**Comment by epicstudios856** [comment]
Android issue, we working to avoid it..

**Comment by epicstudios856** [comment]
issue fixed here!
https://github.com/epicstudios856/Vectras-VM-Android/releases/tag/v2.8.5

**Comment by CreaGab** [comment]
Hi, still not working even with bootstrap file.
![Uploading Screenshot_20240419_094909_Vectras VM.png…]()
